In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns
import statsmodels.formula.api as smf
pd.options.mode.chained_assignment = None
from sklearn.linear_model import LinearRegression
from sklearn.metrics import confusion_matrix

In [118]:
#1.1
df = pd.read_csv("./data/heart.csv")
df.shape #(303, 14)
df.head(5)

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0   63    1   3     145   233    1        0       150     0      2.3    0   
1   37    1   2     130   250    0        1       187     0      3.5    0   
2   41    0   1     130   204    0        0       172     0      1.4    2   
3   56    1   1     120   236    0        1       178     0      0.8    2   
4   57    0   0     120   354    0        1       163     1      0.6    2   

   caa  thall  output  
0    0      1       1  
1    0      2       1  
2    0      2       1  
3    0      2       1  
4    0      2       1

In [119]:
#1.2
df.age.min()#29
df.age.max()#77
df.age.value_counts()
df.sex.value_counts()
df.trtbps.value_counts()
df.chol.value_counts()
df.isna().sum()

age         0
sex         0
cp          0
trtbps      0
chol        0
fbs         0
restecg     0
thalachh    0
exng        0
oldpeak     0
slp         0
caa         0
thall       0
output      0
dtype: int64

In [120]:
#1.3
print("sex, cp, fbs, restecg, exng, output")
df.columns

sex, cp, fbs, restecg, exng, output


Index(['age', 'sex', 'cp', 'trtbps', 'chol', 'fbs', 'restecg', 'thalachh',
       'exng', 'oldpeak', 'slp', 'caa', 'thall', 'output'],
      dtype='object')

In [121]:
#1.4
def change_to_cat(column_name):
    for i in range(len(df[column_name])):
        if df[column_name][i] == 0:
            df[column_name][i] = "zero"
        elif df[column_name][i] == 1:
            df[column_name][i] = "one"
        elif df[column_name][i] == 2:
            df[column_name][i] = "two"
        elif df[column_name][i] == 3:
            df[column_name][i] = "three"
        elif df[column_name][i] == 4:
            df[column_name][i] = "four"
change_to_cat('sex')
change_to_cat('fbs')
change_to_cat('restecg')
change_to_cat('exng')
change_to_cat('cp')
df

age   sex     cp  trtbps  chol   fbs restecg  thalachh  exng  oldpeak  \
0     63   one  three     145   233   one    zero       150  zero      2.3   
1     37   one    two     130   250  zero     one       187  zero      3.5   
2     41  zero    one     130   204  zero    zero       172  zero      1.4   
3     56   one    one     120   236  zero     one       178  zero      0.8   
4     57  zero   zero     120   354  zero     one       163   one      0.6   
..   ...   ...    ...     ...   ...   ...     ...       ...   ...      ...   
298   57  zero   zero     140   241  zero     one       123   one      0.2   
299   45   one  three     110   264  zero     one       132  zero      1.2   
300   68   one   zero     144   193   one     one       141  zero      3.4   
301   57   one   zero     130   131  zero     one       115   one      1.2   
302   57  zero    one     130   236  zero    zero       174  zero      0.0   

     slp  caa  thall  output  
0      0    0      1       1  
1      0    0      2       1  
2      2    0      2       1  
3      2    0      2       1  
4      2    0      2       1  
..   ...  ...    ...     ...  
298    1    0      3       0  
299    1    0      3       0  
300    1    2      3       0  
301    1    1      3       0  
302    1    1      2       0  

[303 rows x 14 columns]

In [122]:
#1.4 cont
m = smf.logit("output ~ age + sex + cp + trtbps + chol + fbs + restecg + thalachh + exng + oldpeak + slp + caa + thall", data=df).fit()
m.params

Optimization terminated successfully.
         Current function value: 0.345478
         Iterations 7


Intercept          2.257239
sex[T.zero]        1.766108
cp[T.three]        0.959423
cp[T.two]          0.844761
cp[T.zero]        -1.192502
fbs[T.zero]        0.011093
restecg[T.two]    -0.836521
restecg[T.zero]   -0.497028
exng[T.zero]       0.902581
age               -0.003799
trtbps            -0.017800
chol              -0.004911
thalachh           0.022030
oldpeak           -0.495638
slp                0.578350
caa               -0.789806
thall             -0.887500
dtype: float64

In [123]:
#1.5
me = m.get_margeff().summary()
me

<class 'statsmodels.iolib.summary.Summary'>
"""
        Logit Marginal Effects       
=====================================
Dep. Variable:                 output
Method:                          dydx
At:                           overall
===================================================================================
                     dy/dx    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------
sex[T.zero]         0.1920      0.048      4.013      0.000       0.098       0.286
cp[T.three]         0.1043      0.080      1.311      0.190      -0.052       0.260
cp[T.two]           0.0918      0.064      1.425      0.154      -0.034       0.218
cp[T.zero]         -0.1297      0.057     -2.266      0.023      -0.242      -0.018
fbs[T.zero]         0.0012      0.059      0.021      0.984      -0.114       0.116
restecg[T.two]     -0.0910      0.242     -0.377      0.706      -0.564       0.382
restecg[T.zero]    -0.0540      0.039     -1.383      0.167      -0.131       0.023
exng[T.zero]        0.0981      0.044      2.237      0.025       0.012       0.184
age                -0.0004      0.003     -0.163      0.871      -0.005       0.005
trtbps             -0.0019      0.001     -1.736      0.083      -0.004       0.000
chol               -0.0005      0.000     -1.285      0.199      -0.001       0.000
thalachh            0.0024      0.001      2.150      0.032       0.000       0.005
oldpeak            -0.0539      0.023     -2.322      0.020      -0.099      -0.008
slp                 0.0629      0.038      1.652      0.098      -0.012       0.137
caa                -0.0859      0.019     -4.533      0.000      -0.123      -0.049
thall              -0.0965      0.030     -3.226      0.001      -0.155      -0.038
===================================================================================
"""

In [124]:
#1.6
#a) Age is not statistically significant in predicting output
#b) Sex does seem to be significant
#c) The reference category is cp[1], cp[3] and cp[2] are highly associated, but not statistically significant, while cp[0] is 
#the lowest in terms of association, but is significant
#d) thall, caa, and oldpeak are all associated with a lower risk of heart attacks. These all intuitevly make sense

In [125]:
#1.7
df["age1"] = pd.cut(df.age,
                      bins = [0, 40, 55, 70, 100],
                      labels = ["0-40", "41-56", "55-70", "71 or more"],
                      right=False)
df.head(2)
m1 = smf.logit("output ~ age1", data = df).fit()
m1.get_margeff().summary()
#The age group 0-30 is the reference category

Optimization terminated successfully.
         Current function value: 0.644412
         Iterations 5


<class 'statsmodels.iolib.summary.Summary'>
"""
        Logit Marginal Effects       
=====================================
Dep. Variable:                 output
Method:                          dydx
At:                           overall
======================================================================================
                        dy/dx    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
age1[T.41-56]         -0.0702      0.137     -0.511      0.609      -0.339       0.199
age1[T.55-70]         -0.3440      0.131     -2.635      0.008      -0.600      -0.088
age1[T.71 or more]    -0.1568      0.195     -0.803      0.422      -0.539       0.226
======================================================================================
"""

In [126]:
#1.8
#Contrary to my initial thoughts, the probability of heart attacks seems to be decreasing as age goes up.
# I think that because of the fact that the majority of people in this group were experiencing chest pain, age becomes
# less of a factor because older people may be more concerned with taking care of these problems, while younger
# people may believe the fallacy that "it can't happen to them yet". This however, is just a guess

In [127]:
#1.9
phat = m.predict(df)
print(phat.loc[:10])

0     0.718029
1     0.719764
2     0.969094
3     0.928890
4     0.806307
5     0.746502
6     0.860697
7     0.867796
8     0.829690
9     0.938545
10    0.603322
dtype: float64


In [128]:
#1.9 cont
#adding a new row
df.loc[len(df.index)] = [60, 'one', 'two', 125, 250, 'one', 'two',df.thalachh.mean(), 'one',df.oldpeak.mean(), df.slp.mean(), 2, df.thall.mean(), 1, '55-70']
phat = m.predict(df)
print(phat.loc[304:304])
#THis person roughly has a 18.8887 of having a heart attack.

Series([], dtype: float64)


In [129]:
#1.9 cont
list = []
for i in range(len(phat)):
    if phat[i] < 0.5:
        list.append(0)
    else:
        list.append(1)
confusion_matrix(df.output, list)

array([[108,  30],
       [ 15, 151]])

In [130]:
#1.9 cont
from sklearn.metrics import accuracy_score
print(accuracy_score(df.output, list))

0.8519736842105263


# 2 Heart attack: predictive modeling (50pt)
Now let’s construct the same model using sklearn package. Remember that
sklearn package requires the matrix of predictor values (X) to be separated from
the vector of outcome variable (y). The predictor values must be a matrix, not
a vector. See Python Notes 11.2.2 for how to use sklearn for logistic regression.


In [200]:
# 2.1
df = pd.read_csv("./data/heart.csv")
from sklearn.linear_model import LogisticRegression

m3 = LogisticRegression(max_iter=5000, penalty="none")

X = df.iloc[:,0:13]
y = df.output
m3.fit(X,y)

print('Intercept: ', m.intercept_)
print('coefficients: ', m.coef_)

Intercept:  [3.41594582]
coefficients:  [[-0.0045197  -1.76965133  0.85824128 -0.01939501 -0.00465682  0.03257686
   0.465879    0.02339507 -1.00530912 -0.5392668   0.57590954 -0.77728811
  -0.89830325]]


2. Predict the probability of having a heart attack P(output = 1|x) for everyone in data. Print out the first 10 probabilities. The results should be
very similar to what you got in 1.9 above.

In [205]:
phat2 =  m3.predict_proba(X)
phat2[:11]

array([[0.19120757, 0.80879243],
       [0.33923417, 0.66076583],
       [0.03762526, 0.96237474],
       [0.08478637, 0.91521363],
       [0.1842181 , 0.8157819 ],
       [0.23694353, 0.76305647],
       [0.16876858, 0.83123142],
       [0.15140035, 0.84859965],
       [0.20737237, 0.79262763],
       [0.07998402, 0.92001598],
       [0.37962684, 0.62037316]])

3. Predict the label (outcome)—that is, whether someone has heart attack
or not, instead of predicting the probability. Print out the first 10 labels.

In [202]:
yhat = m3.predict(X)
yhat[:10]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

4. You can predict labels in two ways: you can use .predict method, or
alternatively, you can compute probabilities and find where they are larger
than 0.5.
Show that both methods give you the same results

In [234]:
(y > 0.5)

0       True
1       True
2       True
3       True
4       True
       ...  
298    False
299    False
300    False
301    False
302    False
Name: output, Length: 303, dtype: bool

In [237]:
y[300]

0

5. Display the confusion matrix. Do you get the same matrix as in 1.9?

In [206]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y, yhat)

array([[106,  32],
       [ 14, 151]])

It's slightly different. There are 2 less true negatives in the first row, but the second row is the exact same as the confusion matrix in 1.9

6. Compute and display precision and recall. What do you think, which
measure–accuracy, precision, recall, or F-score should we try to improve
in order to make this model more applicable in medicine? Explain!


In [210]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

print('precision score: ', precision_score(y, yhat))
print('recall score: ',recall_score(y, yhat))


precision score:  0.825136612021858
recall score:  0.9151515151515152


To make this measure-accuracy better, we should probably try to use recall because recall is the TP/(TP + FN). Since we are talking about predicting a heart attack, there is a high cost associated with the false negative, and recall is better for handling false negatives rather than precision score.

7. Now imagine we create another very simple model (“naive model”) that
predicts everyone the same result (attack or no attack), whichever category
is more common in data (the majority category).
How would the confusion matrix of this model look like? What are the
corresponding accuracy, precision and recall? Explain!
Note: you should not fit any model here, you are able to compute these
all these values manually with just a calculator!


Let's say that our naive model predicts that almost everyone will get a heart attack. The confusion matrix looks like this:

|        |          |          | Predicted |
|:------:|:--------:|:--------:|:---------:|
|        |          | Positive |  Negative |
| Actual | Positive |    138   |     0     |
|        | Negative |    165   |     0     |

The precision of this model is: 138/(138+165), which is about 45.6% precision.

The recall of this model is: 138/(138+0), which is 100% recall.

# How long did we spend?
It took us about 6 hours on the problem set